### ISSUE TITLE
Document which _combination_ of Components are valid

### ISSUE THREAD

**Issue by andrewphilipsmith** [PandemiaProject/pandemia#56]

**Comment by James-Thompson-724** [comment]
-which combinations of components are valid? document this, e.g. in the readme
also:
-test_all_components.yaml not deterministic?
-test scenarios should cover range of epidemiological scenarios
-are test scenarios ok? are components configured in such a way that they produce expected changes in the output?

**Comment by andrewphilipsmith** [comment]
I've re-opened this. I could not find this info in the docs. 

This may be slightly overkill, but as an example I've drafted something along the lines of what I was looking for here:
https://thealanturininstitute-my.sharepoint.com/:x:/g/personal/a_smith_turing_ac_uk/EQzXHVoHF-VKt6GhKDKgOegB7GvMKypgcBiUWdCBMAWILA?e=5fjoVw

This is not complete. It might be possible to both add detail to this and simplify it.

**Comment by James-Thompson-724** [comment]
I've updated the void and default components (see https://github.com/PandemiaProject/pandemia/commit/5f40c20aeb007d3ef21f3ffb813532e4b4503bdb) so that all combinations of components should now execute without errors. Unfortunately I'm having trouble accessing that excel file, but given this update, is something like that still needed?

**Comment by James-Thompson-724** [comment]
How to edit the config file, how the variables in the config relate to what's described in the user guide...

**Comment by James-Thompson-724** [comment]
There's now a couple of sentences in the configuration sections of the docs addressing the previous comment...
